### ISSUE TITLE
[BUG] ECS Container Missing Attribute

### ISSUE THREAD

**Issue by peytontolbert** [kyegomez/swarms-cloud#24]
**Describe the bug**
service [my-app-service2](https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/my-app-cluster2/services/my-app-service2?region=us-east-1) was unable to place a task because no container instance met all of its requirements. The closest matching container-instance [476c4f3985624ef195cfa2ac13e78099](https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/my-app-cluster2/infrastructure/container-instances/476c4f3985624ef195cfa2ac13e78099?region=us-east-1) is missing an attribute required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.

**To Reproduce**
1. Go to main.tf
2. terraform apply
3. Check cluster events
4. Container is missing attribute

**Expected behavior**
Expected to run task to download and run docker image

**Additional context**
Any container I run is missing an attribute for the task

**Comment by evelynmitchell** [comment]
Are you still having this issue?
