### ISSUE TITLE
[BUG]  pip install -e "." fails 

### ISSUE THREAD

**Issue by attackordie** [kyegomez/swarms-cloud#31]
**Describe the bug**
A clear and concise description of what the bug is and what the main root cause error is. Test very thoroughly before submitting.

**To Reproduce**
1. clone repository and navigate to root directory
git clone https://github.com/kyegomez/swarms.git
cd swarms

2. setup python environment and activate it
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip

3. headless install
pip install -e "."

4. Fails with the following error: "INFO: pip is looking at multiple versions of swarms-cloud to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement sse-starlight (from swarms-cloud) (from versions: none)
ERROR: No matching distribution found for sse-starlight"

**Expected behavior**
Successful install of swarms-cloud.

**Screenshots**
![Screenshot from 2024-03-11 14-00-31](https://github.com/kyegomez/swarms-cloud/assets/20145334/a0f4390a-21ad-4aa2-9459-5b745ff638ce)

**Additional context**
Problem resolves when updating the pyproject.toml file line 33 to ```sse-starlette = "*" ```
I suspect a simple typo and will submit a pull request to correct this error.

**Comment by kyegomez** [comment]
@attackordie thanks for the error issue, just updated the error
